name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the Next.js app
        run: npm run build

      - name: Debug - Check build output
        run: |
          echo "=== Checking .next directory ==="
          ls -la .next/ || echo "❌ .next directory not found"
          
          echo "=== Checking standalone directory ==="
          ls -la .next/standalone/ || echo "❌ .next/standalone directory not found"
          
          echo "=== Checking standalone contents ==="
          if [ -d ".next/standalone" ]; then
            find .next/standalone -type f -name "*.js" | head -10
            echo "Standalone directory size:"
            du -sh .next/standalone/
          fi
          
          echo "=== Checking for server.js in standalone ==="
          ls -la .next/standalone/server.js || echo "❌ server.js not found in standalone"
          
          echo "=== Checking static files ==="
          ls -la .next/static/ || echo "❌ .next/static directory not found"

      - name: Prepare deployment files
        run: |
          mkdir -p output
          
          # Copy standalone files
          if [ -d ".next/standalone" ]; then
            echo "✅ Copying standalone files..."
            cp -r .next/standalone/* output/
            
            # Copy .next directory from standalone
            if [ -d ".next/standalone/.next" ]; then
              echo "✅ Copying .next from standalone..."
              cp -r .next/standalone/.next output/
            else
              echo "⚠️  .next not found in standalone, copying from build..."
              mkdir -p output/.next
              cp -r .next/static output/.next/ || echo "No static files found"
              cp -r .next/*.json output/.next/ || echo "No JSON files found"
            fi
          else
            echo "❌ Standalone directory not found!"
            exit 1
          fi
          
          # Copy public directory to output root (not inside .next)
          if [ -d "public" ]; then
            echo "✅ Copying public directory..."
            cp -r public output/
          else
            echo "⚠️  Public directory not found"
          fi
          
          # Copy static files to public/_next/static for proper serving
          if [ -d ".next/static" ] && [ -d "output/public" ]; then
            echo "✅ Copying static files to public/_next/static..."
            mkdir -p output/public/_next
            cp -r .next/static output/public/_next/
          fi
          
          echo "=== Final output structure ==="
          find output -type f | head -20

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: output

      - name: Debug deployment package
        run: |
          echo "=== Deployment package contents ==="
          ls -la output/
          echo "=== Looking for server.js ==="
          ls -la output/server.js || echo "❌ server.js not found in deployment package"
          echo "=== Looking for package.json ==="
          ls -la output/package.json || echo "❌ package.json not found in deployment package"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'xaltrisWA'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./output