name: Build and deploy Next.js app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the Next.js app
        run: npm run build

      - name: Verify standalone build
        run: |
          echo "=== Checking build output ==="
          ls -la .next/
          echo ""
          echo "=== Checking standalone directory ==="
          if [ -d ".next/standalone" ]; then
            echo "✅ Standalone build created successfully"
            ls -la .next/standalone/
            echo ""
            echo "Standalone structure:"
            find .next/standalone -name "*.js" -o -name "*.json" | head -10
          else
            echo "❌ Standalone build not found!"
            exit 1
          fi

      - name: Prepare deployment package
        run: |
          echo "Creating deployment package..."
          mkdir -p deployment
          
          # Copy standalone application
          cp -r .next/standalone/* deployment/
          
          # Copy static files to deployment/.next/static
          if [ -d ".next/static" ]; then
            mkdir -p deployment/.next/static
            cp -r .next/static/* deployment/.next/static/
          fi
          
          # Copy public directory
          if [ -d "public" ]; then
            cp -r public deployment/
          fi
          
          echo "=== Deployment package contents ==="
          ls -la deployment/
          echo ""
          echo "=== Checking for required files ==="
          ls -la deployment/server.js && echo "✅ server.js found" || echo "❌ server.js missing"
          ls -la deployment/package.json && echo "✅ package.json found" || echo "❌ package.json missing"
          ls -la deployment/.next/ && echo "✅ .next directory found" || echo "❌ .next directory missing"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: .

      - name: Verify deployment package
        run: |
          echo "=== Deployment package verification ==="
          ls -la
          echo ""
          echo "Package.json contents:"
          cat package.json | grep -A 5 -B 5 "scripts" || echo "No scripts section found"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'xaltrisWA'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .